version: "2.3"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # comment this to debug
    command: mongod --quiet --logpath /dev/null

  api:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./src:/usr/app
    command: uvicorn --host 0.0.0.0 main:app --reload
    environment:
      - DATABASE_URL=mongodb://root:example@mongo
    links:
      - mongo